### ISSUE TITLE
(docs): Release notes link for 0.4 points to outdated version 

### ISSUE THREAD

**Issue by desktophero** [Cargill/splinter#1145]
Release notes page in Splinter Docs advertises v0.4 is released but `RELEASE_NOTES.md` in `master` in Splinter repo is `0.3.18`

https://splinter.dev/releases/0.4/ links to https://github.com/Cargill/splinter/blob/master/RELEASE_NOTES.md

This PR looks like it includes the content just doesn't target `master` https://github.com/Cargill/splinter/pull/933

I can submit a PR to update one of the sections so the docs and the repo are aligned.

**Comment by vaporos** [comment]
The 0.4 release notes page should be pointing to https://github.com/Cargill/splinter/blob/0-4/RELEASE_NOTES.md.

The lack of duplication between 0-4 and master was intentional as currently the process is to add the release notes only in the branch where the release occurred. So For 0.4, that would be in the 0-4 branch. The thinking was that if we had 0-4, 0-6, 0-8, master that we wouldn't want release activity of 0-4 to touch 0-6, 0-8, master branches. (Processes can be evolve though, if we need a different outcome.)

**Comment by rbuysse** [comment]
Fixed in https://github.com/Cargill/splinter-docs/pull/214
