### ISSUE TITLE
Gameroom setup fails with `'--rest-api-endpoint' which wasn't expected`

### ISSUE THREAD

**Issue by txross** [Cargill/splinter#832]
Steps:
```
pwd
# /c/Users/rossth/git/github.com/Cargill/splinter
git fetch origin
git checkout v0.3.17
docker-compose -f examples/gameroom/docker-compose.yaml up -d
docker logs -f splinterd-node-acme
```

Output:
```
psql: could not connect to server: Connection refused
        Is the server running on host "splinterd-db-acme" (23.217.138.110) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "splinterd-db-acme" (23.202.231.169) and accepting
        TCP/IP connections on port 5432?
Database is unavailable - sleeping
Successfully applied biome credentials migrations
Writing file: /etc/splinter/certs/generated_ca.pem
Writing file: /etc/splinter/certs/private/generated_ca.key
Writing file: /etc/splinter/certs/client.crt
Writing file: /etc/splinter/certs/private/client.key
Writing file: /etc/splinter/certs/server.crt
Writing file: /etc/splinter/certs/private/server.key
error: Found argument '--rest-api-endpoint' which wasn't expected, or isn't valid in this context

USAGE:
    splinterd --advertised-endpoints <advertised_endpoints>... --config <config> --database <database> --network-endpoints <network_endpoints>... --service-endpoint <service_endpoint> --verbose

For more information try --help
```

**Comment by leebradley** [comment]
This is a somewhat stale issue that is not necessarily a bug so much as a result of Docker caching.

The problem here is the gameroom demo Docker images are constructed from your git checkout, but they don't automatically rebuild themselves if the code updates. It appears as though you had previously started the gameroom demo and built the docker images. When you switched to the v0.3.17 tag, git updated `docker-compose.yaml` to call splinterd using the newly-created `--rest-api-endpoint` argument, but your docker image remained on a version of splinterd built without that support.

To fix, you want to run docker-compose with the `--build` and `--force-recreate` arguments to update your docker images.

**Comment by peterschwarz** [comment]
Closing this issue as it has been addressed here with additional comments.  Please re-open if the issue still persists.
